name: Docs
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml doxygen
          curl -sSL https://github.com/sass/dart-sass/releases/download/1.49.7/dart-sass-1.49.7-linux-x64.tar.gz | tar -xzvf - --strip-components=1 -C ~/.local/bin dart-sass/sass
          pip install sphinx sphinx_rtd_theme sphinxcontrib-plantuml sphinxcontrib-doxylink
      - name: Sphinx build
        run: |
          mkdir doc_duild
          sphinx-build doc doc_duild
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc_duild/
          force_orphan: true
