name: Docs
on: [push, pull_request, workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y plantuml doxygen
          pip install sphinx sphinx_rtd_theme sphinxcontrib-plantuml sphinxcontrib-doxylink doxysphinx
      - name: Sphinx build
        run: |
          doxygen doc/doxygen/Hello/Doxyfile
          doxysphinx build doc doc_build doc/doxygen/Hello/Doxyfile
          sphinx-build -a doc doc_build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc_duild/
          force_orphan: true
